
server:
  port: 8080

spring:
  application:
    name: dl-article
  profiles:
    active: local

  datasource:
    driver-class-name:
    url: jdbc:mariadb://localhost:3306/danlab-article
    username: jus
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: test


---
spring.config.activate.on-profile: prod