server:
  port: 8080

spring:
  application:
    name: dl-article
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.100.44.38:3306/jwt_security?serverTimezone=Asia/Seoul
    username: root
    password: hks13579

  jpa:
    properties:
      hibernate:
        ddl-auto: update

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: test

---
spring.config.activate.on-profile: prod