
server:
  port: 8080

spring:
  application:
    name: dl-article
  profiles:
    active: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://article-postgres:5432/danlab?serverTimezone=Asia/Seoul
    username: jus
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: test


---
spring.config.activate.on-profile: prod