- hosts: all
  #   become: true

  tasks:
    - name: create a docker image with deployed jar file
      command: docker build -t leejusung/article-server .
      args:
        chdir: /root/dl-article

    - name: push the image on Docker Hub
      command: docker push leejusung/article-server

    - name: remove the docker image from the ansible server
      command: docker rmi leejusung/article-server
      ignore_errors: yes